# Generated by Django 5.2.4 on 2025-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='any',
            field=models.BooleanField(default=False),
        ),
    ]
