# Generated by Django 5.2.4 on 2025-07-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_any'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='any',
        ),
    ]
